[[fetch]]
files = [
    "ltk/__init__.py",
    "ltk/jquery.py",
    "ltk/widgets.py",
    "ltk/ltk.js",
    "ltk/ltk.css",
    "examples/__init__.py",
    "examples/app.py",
    "examples/documentation.py",
    "examples/helloworld.py",
    "examples/inputs.py",
    "examples/pydata.py",
    "examples/tictactoe.py",
    "examples/tictactoe.css",
    "examples/custom.py",
    "examples/table.py",
]